### PR TITLE
Consignment conceal procedure

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Companion to https://github.com/rgb-org/rgb-core/pull/22

### CODE REVIEW

**Comment by claudiosdc** [comment]
Here are my comments after reviewing the solution.

I have tested the updated version of RGB Node via the CLI, and the solution (for locally accepting the transfer so asset change allocations get recorded) seems to work as intended.

However, from an end user's stand point it does not seem to be very practical. For me to be able to accept the consignment locally (saved to the `xxxx.revealed.rgb` file), I had to resource to the `rgb` command line tool to read the contents of the consignment file and retrieve the blinding factor associated with the asset change outpoint, since that is required when issuing the `fungible accept` CLI command.

It would be better if that information (the asset change outpoint blinding factor) was directly returned by the `fungible transfer` CLI command, similarly how the receiver's outpoint blinding factor is returned by the `fungible blind` CLI command.

**Comment by rajarshimaitra** [comment]
>However, from an end user's stand point it does not seem to be very practical. For me to be able to accept the consignment locally (saved to the xxxx.revealed.rgb file), I had to resource to the rgb command line tool to read the contents of the consignment file and retrieve the blinding factor associated with the asset change outpoint, since that is required when issuing the fungible accept CLI command.

My understanding is end-users will not use the CLI, at least in its current form to do these operations. It will be handled by wallets. And they can store and retrieve relevant information programmatically.

So I think making the CLI extra efficient will not result in many benefits as it's not intended to be used by end-users anyway.

I do think we also need to update the demo doc so devs can run through this process.

**Comment by claudiosdc** [comment]
> My understanding is end-users will not use the CLI, at least in its current form to do these operations. It will be handled by wallets. And they can store and retrieve relevant information programmatically.

@rajarshimaitra, when I say "end user", I mean any one who is in possession of the library/program and intends to use it. I understand that most likely it will be software developers, like myself, who will do it, but that does not mean that we should make their lives harder if we can avoid it.

> So I think making the CLI extra efficient will not result in many benefits as it's not intended to be used by end-users anyway.

@rajarshimaitra, I would not classify exposing a simple piece of information as "making the CLI extra efficient." The effort for doing it is certainly small.

**Comment by rajarshimaitra** [comment]
>when I say "end user", I mean any one who is in possession of the library/program and intends to use it. I understand that most likely it will be software developers

Well, then I misunderstood that part. Yes, it does make sense to have the blinding factors returned for easier dev flows. 

ACK.

**Comment by dr-orlovsky** [comment]
@claudiosdc, yeah, cli is purly debugging tool not intended to be used outside of those working on RGB development (even for wallet devs). But I do agree that the current design with two consignments is suboptimal. I just had to do something as less intrusive as possible to have the current version fixed and get v0.4 published before doing something more optimized for v0.5.

My current plan addressing the issue is:
- Instead of doing two consignment, introduce a special `Disclosure` type (at the `stash` mod) which will not be shared outside and intendet only to persists local changes to stash externally to the stash itself. Rationale:
    * Consignment will grow large, exporting most of stash asset data and then merging it back without any good reason
    * It's a bad practice to import external large binary file (`consignment`) back into the stash w/o validation, which will produce even more unnecessary load (disclosure validation can be much simplier)
    * Disclosures were planned anyway for exposing/proving facts about the stash for those who already know the history but only had some data concealed (like issuer may conceal some of the information in case of non-RGB20 assets or smart contracts and be able to reveal it later with disclosures - for instance you can build a lottery smart contract based on that)

If it is still desirable to have cli fixed in v0.4 it can be done, since underlying API does not require secret to be presented (it's a vector which van be 0-elements), so it should be just couple of lines PR.

**Comment by claudiosdc** [comment]
> @claudiosdc, yeah, cli is purly debugging tool not intended to be used outside of those working on RGB development (even for wallet devs). But I do agree that the current design with two consignments is suboptimal. I just had to do something as less intrusive as possible to have the current version fixed and get v0.4 published before doing something more optimized for v0.5.
> 
> My current plan addressing the issue is:
> 
> * Instead of doing two consignment, introduce a special `Disclosure` type (at the `stash` mod) which will not be shared outside and intendet only to persists local changes to stash externally to the stash itself. Rationale:
>   
>   * Consignment will grow large, exporting most of stash asset data and then merging it back without any good reason
>   * It's a bad practice to import external large binary file (`consignment`) back into the stash w/o validation, which will produce even more unnecessary load (disclosure validation can be much simplier)
>   * Disclosures were planned anyway for exposing/proving facts about the stash for those who already know the history but only had some data concealed (like issuer may conceal some of the information in case of non-RGB20 assets or smart contracts and be able to reveal it later with disclosures - for instance you can build a lottery smart contract based on that)

I see your point.
 
> If it is still desirable to have cli fixed in v0.4 it can be done, since underlying API does not require secret to be presented (it's a vector which van be 0-elements), so it should be just couple of lines PR.

Well, I would feel better if we did not need to dig up the asset change outpoint blinding factor from the revealed consignment to accept it locally.

**Comment by dr-orlovsky** [comment]
Here you are: https://github.com/rgb-org/rgb-node/pull/147

**Pull request merged**
